# Generated by Django 4.2.1 on 2023-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_code', models.CharField(db_column='Group_Code', max_length=20, primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_column='Group_Name', max_length=10)),
                ('creator_id', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_column='Creator_ID', max_length=100)),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
    ]
